version: 2
updates:
  # Define update settings for different package managers (e.g., npm, bundler, pip, etc.)
  - package-ecosystem: "npm"  # Replace with your package manager (e.g., bundler, pip)
    directory: "/"           # Specify the directory where your dependencies are located
    schedule:
      interval: "daily"     # Specify how often Dependabot should check for updates
    # Define which types of updates to allow
    allow:
      - update-types: ["security", "dependencies"]
        # Optionally, you can specify version requirements for allowed updates
        versions: ["*"]
